# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew shadowJar
    - name: Upload Paper build
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Paper
        # A file, directory or wildcard pattern that describes what to upload
        path: wolfstats-paper/build/libs/wolfstats-paper-*-all.jar
    - name: Upload Velocity build
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Velocity
        # A file, directory or wildcard pattern that describes what to upload
        path: wolfstats-velocity/build/libs/wolfstats-velocity-*-all.jar
